server:
  port: 8181

# MySQL 데이터베이스 설정
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    # show_sql: true

  profiles:
    include: oauth, real-db

  session:
    store-type: jdbc

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

#   sql:
#     init:
#       mode: always

logging:
  level:
    org.hibernate.SQL: debug
