server:
  port: 8181

# MySQL 데이터베이스 설정
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myproject?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#    show_sql: true

  profiles:
    include: oauth

  session:
    store-type: jdbc

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

loggin:
  level:
    org.hibernate.SQL: debug