server:
  port: 8181

# MySQL 데이터베이스 설정
spring:
  datasource:
    url: mariadb://spring.ccyq29jlogrs.ap-northeast-2.rds.amazonaws.com:3306/spring
    username: hahyuning 
    password: qlalfqjsgh88!
    driver-class: org.mariadb.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    # show_sql: true

  profiles:
    include: oauth, real-db

  session:
    store-type: jdbc

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

#   sql:
#     init:
#       mode: always

logging:
  level:
    org.hibernate.SQL: debug
